[package]
name = "RustPrimeNumberLibrary"
version = "0.1.0"
authors = ["Muhammad Hamza Farooq <mhamza2021999@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/RustPrimeNumberLibrary/0.1.o/RustPrimeNumberLibrary/"
repository = "https://github.com/RustPrimeNumberLibrary"
homepage = "https://crates.io/crates/RustPrimeNumberLibrary"
description = "Rust prime number checker library now step 1 is importing create and calling function and put one parameter. This prameter data type is u32"
license = "MIT"
readme = "readme.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
